### ISSUE TITLE
include a sample app with one model

### ISSUE THREAD

**Issue by olivierdalang** [wq/wq-django-template#27]
Hi !

For seasoned Django devs, it's quite straightforward, but it could still be useful to have a very simple `example` app with one `ExampleModel` already registered to work out of the box.

In my particular case, I couldn't figure out how to make the model editable (despite having all permissions, I can't add new items nor edit existing one from the JS). I guess I missed something in the docs, but it would have been much easier to start with an existing working model.

For advanced users, it's not too much bloat to get rid of (just the whole `example` app folder, and one line in settings.py).
 
Thanks !!

**Comment by sheppard** [comment]
Yes, I agree that a default app would be good.  I'd probably give it the two models used in the wq.start test suite ([location](https://github.com/wq/wq.start/blob/master/tests/location.csv) + [observation](https://github.com/wq/wq.start/blob/master/tests/observation.csv)) since that can also demonstrate the client-side foreign key support.

As far as not being able to edit, there are supposed to be flags like `can_add` / `can_change` / etc. that are applied to the wq configuration object upon authentication.  If these aren't coming through even when you are a superuser, then there may be a bug somewhere.

**Comment by olivierdalang** [comment]
@sheppard Ok so it's a bug then :-) I'm not really sure on which repo to create the issue though ? (wq, or wq.app, or wq.db ?)

I get the add/edit functionality when adding `can_add=True` `can_edit=True` as arguments in rest.router.register_model (rest.py).

**Comment by sheppard** [comment]
In this case, the bug is in wq.app.  In general, any of the main repos are fine since we can move issues around.
